export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_STOCK_CATEGORIES_START = 'GET_STOCK_CATEGORIES_START';
export const GET_STOCK_CATEGORIES_SUCCESS = 'GET_STOCK_CATEGORIES_SUCCESS';
export const GET_STOCK_CATEGORIES_FAILURE = 'GET_STOCK_CATEGORIES_FAILURE';

export const GET_PROMO_CATEGORIES_START = 'GET_PROMO_CATEGORIES_START';
export const GET_PROMO_CATEGORIES_SUCCESS = 'GET_PROMO_CATEGORIES_SUCCESS';
export const GET_PROMO_CATEGORIES_FAILURE = 'GET_PROMO_CATEGORIES_FAILURE';
