export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_FOR_PRODUCTS_START = 'GET_FOR_PRODUCTS_START';
export const GET_FOR_PRODUCTS_SUCCESS = 'GET_FOR_PRODUCTS_SUCCESS';
export const GET_FOR_PRODUCTS_FAILURE = 'GET_FOR_PRODUCTS_FAILURE';

export const GET_PROMO_PRODUCTS_START = 'GET_PROMO_PRODUCTS_START';
export const GET_PROMO_PRODUCTS_SUCCESS = 'GET_PROMO_PRODUCTS_SUCCESS';
export const GET_PROMO_PRODUCTS_FAILURE = 'GET_PROMO_PRODUCTS_FAILURE';
export const SET_VIEW_COUNT = 'SET_VIEW_COUNT';

export const GET_PRODUCT_INFO_START = 'GET_PRODUCT_INFO_START';
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS';
export const GET_PRODUCT_INFO_FAILURE = 'GET_PRODUCT_INFO_FAILURE';

export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
