export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const SET_VIEW_COUNT = 'SET_VIEW_COUNT';

export const GET_PRODUCT_INFO_START = 'GET_PRODUCT_INFO_START';
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS';
export const GET_PRODUCT_INFO_FAILURE = 'GET_PRODUCT_INFO_FAILURE';
